# Generated by Django 5.0.1 on 2024-01-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_mymodeltranslation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelTranslation',
        ),
    ]
